[package]
name = "egui_tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.24"
egui = "0.21"
lazy_static = "1.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
unicode-segmentation = "1.10.1"

[dev-dependencies]
eframe = "0.21"
